### ISSUE TITLE
gdh

### ISSUE THREAD

**Issue by jo-seungho** [codestates/MARE#24]
### ISSUE

- 그룹 : `client` , `server`
- 타입 : `bugfix`, `feature`, `delete`
- 상세설명 : 작업의 상세 설명을 기입합니다. ex) 즐겨찾기 버튼 구현

### TODO

- [ ]  해야할 작업을 작성합니다.
- [ ]  ex) 컴포넌트 구현
- [ ]  ex) 서버로 전달 구현

### Labels

- `소요시간`, `그룹`, `스프린트`, `중요도`

!!! 업로드시 아래의 내용을 지우고 업로드합니다. !!!
```jsx
소요시간은 아래의 양식을 참고하여 작성합니다.
`E:1h`, `E:1.5h`, `E:2h`
그룹은 ISSUE에서 작성된 그룹을 참고합니다.
`client`, `server`
스프린트는 구글 캘린더의 현재 스프린트를 참고합니다.
`sprint_2`, `sprint_3`
중요도는 해당 작업의 중요도로, 아래를 참고하여 작성합니다.
`low`, `middle`, `high`
```
