### ISSUE TITLE
[TASK] 랜딩 페이지 제작

### ISSUE THREAD

**Issue by CHOI-K-ROCK** [codestates/MARE#55]
### ISSUE

- 그룹 : `client`
- 타입 : `feature`
- 상세설명 : 첫 방문시 보여질 서비스 설명과 로그인 및 회원가입 링크가 작성된 페이지를 제작합니다.

### TODO

- [ ]  서비스 소개 문구 작성
- [ ]  화면 디자인
- [ ]  로그인 / 회원가입 창으로 라우트
- [ ]  하단 이동 메뉴 컴포넌트 연결

### Labels

- `E:1.5h`, `client`, `sprint_2`, `low`
