### ISSUE TITLE
[TASK] 계정 정보 컴포넌트 구현

### ISSUE THREAD

**Issue by jo-seungho** [codestates/MARE#57]
### ISSUE

- 그룹 : `client` 
- 타입 : `feature`
- 상세설명 : 유저의 정보를 볼 수 있으며 닉네임과 비밀번호를 수정 및 회원탈퇴를 할 수 있는 페이지를 구현합니다

### TODO

- [ ] 유저의 닉네임, 이름, 이메일이 표시됩니다
- [ ] 닉네임을 수정할 수 있습니다
- [ ] 비밀번호를 수정할 수 있습니다
- [ ] 회원탈퇴를 요청할 경우 유저의 정보를 삭제하고 성공 여부를 화면에 표시합니다
- [ ] 하단 이동 메뉴 컴포넌트 연결

### Labels

- `client`, `sprint_2`,  `high`
