### ISSUE TITLE
[TASK] 작성된 레시피 표시 컴포넌트 구현

### ISSUE THREAD

**Issue by CHOI-K-ROCK** [codestates/MARE#62]
### ISSUE

- 그룹 : `client`
- 타입 : `feature`
- 상세설명 : 작성된 레시피의 정보를 불러와, 해당 레시피의 상세정보로 이동 할 수 있는 버튼의 컴포넌트를 구현합니다.

### TODO

- [ ]  서버에서 받아온 정보를 기반으로, 사진과 레시피의 제목을 함께 표시합니다. - props 이용
- [ ] 해당 버튼을 누른 경우 해당하는 레시피의 상세 페이지로 이동합니다.
- [ ] 서버에서 받은 응답을 기반으로 즐겨찾기 여부를 아이콘으로 표시합니다.

### Labels

- `E:1.5h`, `client`, `sprint_2`, `middle`
