### ISSUE TITLE
[TASK] 모달 컴포넌트 구현

### ISSUE THREAD

**Issue by CHOI-K-ROCK** [codestates/MARE#72]
### ISSUE

- 그룹 : `client`
- 타입 : `feature`
- 상세설명 : 어떤 오류가 발생했을 때, alert 창 대신, 모달을 이용하여 메세지를 표시합니다.

### TODO

- [ ]  로그인 혹은 비밀번호 확인 시 비밀번호가 틀린경우의 모달
- [ ]  업로드 실패시 모달 
- [ ]  로딩 서클 모달

### Labels

- `E:1.5h`, `client, `sprint_2`, `low`
